/**
 * Thin, typed HTTP client for the Mission Control service seam.
 *
 * Every request/response shape below is derived from `./schema.ts`, which is
 * generated by `openapi-typescript` against the seam's live `/openapi.json`
 * (see `npm run gen:api`). Nothing here is hand-transcribed — if the seam's
 * OpenAPI contract changes, regenerate the schema and the compiler flags the
 * drift.
 *
 * This module is deliberately dumb: it builds URLs, serialises JSON, and
 * surfaces typed results/errors. It renders nothing and decides nothing.
 *
 * Base URL is env-only (`VITE_MC_SERVICE_BASE_URL`) — never a hardcoded host,
 * account, or external system. In the dev/prod topology the SPA is served
 * same-origin (Vite dev-proxy in dev, FastAPI StaticFiles in prod), so the
 * variable is normally unset in the browser and requests go same-origin with
 * relative paths. When it *is* set, the browser targets the seam directly
 * (which requires the seam to permit CORS).
 */
import type { components, operations } from './schema'

// ---------------------------------------------------------------------------
// Public types (re-exported straight from the generated schema)
// ---------------------------------------------------------------------------

/** All OpenAPI component schemas, keyed by name. */
export type Schemas = components['schemas']

export type LaunchRequest = Schemas['LaunchRequest']
export type RunList = Schemas['RunList']
export type RunDetail = Schemas['RunDetail']
export type ChildRunModel = Schemas['ChildRunModel']
export type DecisionResponse = Schemas['DecisionResponse']
export type TargetList = Schemas['TargetList']
export type MetricsResponse = Schemas['MetricsResponse']
export type OpenPlanRequest = Schemas['OpenPlanRequest']
export type PlanList = Schemas['PlanList']
export type PlanSummary = Schemas['PlanSummary']
export type PlanDetail = Schemas['PlanDetail']
export type TurnRequest = Schemas['TurnRequest']
export type TurnResponse = Schemas['TurnResponse']
export type TurnModel = Schemas['TurnModel']
export type HTTPValidationError = Schemas['HTTPValidationError']

/** Query params for the paged/sorted/time-filtered list endpoints. */
export type ListRunsQuery = NonNullable<
  operations['list_runs_runs_get']['parameters']['query']
>
export type ListPlansQuery = NonNullable<
  operations['list_plans_plans_get']['parameters']['query']
>
export type MetricsQuery = NonNullable<
  operations['metrics_metrics_get']['parameters']['query']
>

/**
 * `GET /runs/{id}/changes` returns a free-form JSON object (the go/no-go
 * change set) in the OpenAPI contract, so it is typed as such rather than
 * invented here. The Gate/Run-station unit narrows it as needed.
 */
export type RunChanges =
  operations['run_changes_runs__run_id__changes_get']['responses']['200']['content']['application/json']

// ---------------------------------------------------------------------------
// Config + error surface
// ---------------------------------------------------------------------------

/**
 * Seam base URL, env-only. Trailing slashes are trimmed so `${BASE_URL}${path}`
 * is always well formed. Empty string ⇒ same-origin (the proxied dev/prod norm).
 */
const BASE_URL = (import.meta.env.VITE_MC_SERVICE_BASE_URL ?? '').replace(/\/+$/, '')

/** Thrown for any non-2xx response. Carries the parsed error body when present. */
export class ApiError extends Error {
  readonly status: number
  readonly statusText: string
  readonly url: string
  readonly body: unknown

  constructor(status: number, statusText: string, url: string, body: unknown) {
    super(`Mission Control API ${status} ${statusText} for ${url}`)
    this.name = 'ApiError'
    this.status = status
    this.statusText = statusText
    this.url = url
    this.body = body
  }
}

/** Per-call knobs. `signal` lets TanStack Query cancel in-flight requests. */
export interface RequestOptions {
  signal?: AbortSignal
}

type QueryValue = string | number | boolean | null | undefined
type QueryParams = Record<string, QueryValue>

function buildUrl(path: string, query?: QueryParams): string {
  const url = `${BASE_URL}${path}`
  if (!query) return url
  const search = new URLSearchParams()
  for (const [key, value] of Object.entries(query)) {
    if (value === undefined || value === null) continue
    search.append(key, String(value))
  }
  const qs = search.toString()
  return qs ? `${url}?${qs}` : url
}

interface RequestInternal {
  query?: QueryParams
  body?: unknown
  signal?: AbortSignal
}

async function request<T>(
  method: string,
  path: string,
  { query, body, signal }: RequestInternal = {},
): Promise<T> {
  const url = buildUrl(path, query)
  const headers: Record<string, string> = { Accept: 'application/json' }
  const init: RequestInit = { method, headers, signal }
  if (body !== undefined) {
    headers['Content-Type'] = 'application/json'
    init.body = JSON.stringify(body)
  }

  const response = await fetch(url, init)

  if (!response.ok) {
    throw new ApiError(response.status, response.statusText, url, await readBody(response))
  }
  // 204/205 or empty body ⇒ nothing to parse.
  if (response.status === 204 || response.status === 205) {
    return undefined as T
  }
  return (await response.json()) as T
}

async function readBody(response: Response): Promise<unknown> {
  try {
    return await response.json()
  } catch {
    try {
      return await response.text()
    } catch {
      return null
    }
  }
}

const enc = encodeURIComponent

// ---------------------------------------------------------------------------
// Runs — Fleet, Launch, Run station
// ---------------------------------------------------------------------------

/** `GET /runs` — paged/sorted/time-filtered fleet list. */
export function listRuns(query?: ListRunsQuery, opts?: RequestOptions): Promise<RunList> {
  return request<RunList>('GET', '/runs', { query, signal: opts?.signal })
}

/** `POST /runs` — launch a run. */
export function launchRun(body: LaunchRequest, opts?: RequestOptions): Promise<RunDetail> {
  return request<RunDetail>('POST', '/runs', { body, signal: opts?.signal })
}

/** `GET /runs/{id}` — run detail. */
export function getRun(runId: string, opts?: RequestOptions): Promise<RunDetail> {
  return request<RunDetail>('GET', `/runs/${enc(runId)}`, { signal: opts?.signal })
}

/** `GET /runs/{id}/changes` — go/no-go change set for the gate. */
export function getRunChanges(runId: string, opts?: RequestOptions): Promise<RunChanges> {
  return request<RunChanges>('GET', `/runs/${enc(runId)}/changes`, { signal: opts?.signal })
}

/** `POST /runs/{id}/approve` — gate: approve. */
export function approveRun(runId: string, opts?: RequestOptions): Promise<DecisionResponse> {
  return request<DecisionResponse>('POST', `/runs/${enc(runId)}/approve`, { signal: opts?.signal })
}

/** `POST /runs/{id}/reject` — gate: reject. */
export function rejectRun(runId: string, opts?: RequestOptions): Promise<DecisionResponse> {
  return request<DecisionResponse>('POST', `/runs/${enc(runId)}/reject`, { signal: opts?.signal })
}

/** `POST /runs/{id}/scrub` — abort before commit. */
export function scrubRun(runId: string, opts?: RequestOptions): Promise<DecisionResponse> {
  return request<DecisionResponse>('POST', `/runs/${enc(runId)}/scrub`, { signal: opts?.signal })
}

/** `POST /runs/{id}/cancel` — cancel an in-flight run. */
export function cancelRun(runId: string, opts?: RequestOptions): Promise<DecisionResponse> {
  return request<DecisionResponse>('POST', `/runs/${enc(runId)}/cancel`, { signal: opts?.signal })
}

// ---------------------------------------------------------------------------
// Targets + Metrics
// ---------------------------------------------------------------------------

/** `GET /targets` — known deploy targets (Fleet filters). */
export function listTargets(opts?: RequestOptions): Promise<TargetList> {
  return request<TargetList>('GET', '/targets', { signal: opts?.signal })
}

/** `GET /metrics` — aggregate metrics, optionally scoped by target/time window. */
export function getMetrics(query?: MetricsQuery, opts?: RequestOptions): Promise<MetricsResponse> {
  return request<MetricsResponse>('GET', '/metrics', { query, signal: opts?.signal })
}

// ---------------------------------------------------------------------------
// Plans — Plan list, Planner
// ---------------------------------------------------------------------------

/** `GET /plans` — paged/sorted plan list. */
export function listPlans(query?: ListPlansQuery, opts?: RequestOptions): Promise<PlanList> {
  return request<PlanList>('GET', '/plans', { query, signal: opts?.signal })
}

/** `POST /plans` — open a new planning session. */
export function openPlan(body: OpenPlanRequest, opts?: RequestOptions): Promise<PlanDetail> {
  return request<PlanDetail>('POST', '/plans', { body, signal: opts?.signal })
}

/** `GET /plans/{id}` — plan detail (transcript + live plan panel). */
export function getPlan(planId: string, opts?: RequestOptions): Promise<PlanDetail> {
  return request<PlanDetail>('GET', `/plans/${enc(planId)}`, { signal: opts?.signal })
}

/** `POST /plans/{id}/turns` — append a planner turn (non-streaming). */
export function appendPlanTurn(
  planId: string,
  body: TurnRequest,
  opts?: RequestOptions,
): Promise<TurnResponse> {
  return request<TurnResponse>('POST', `/plans/${enc(planId)}/turns`, {
    body,
    signal: opts?.signal,
  })
}

/** `POST /plans/{id}/finalize` — finalize the plan. */
export function finalizePlan(planId: string, opts?: RequestOptions): Promise<PlanDetail> {
  return request<PlanDetail>('POST', `/plans/${enc(planId)}/finalize`, { signal: opts?.signal })
}

/**
 * `POST /plans/{id}/turns/stream` — append a planner turn and stream the reply.
 *
 * This is a POST (a request body carries the turn), so the browser's native
 * `EventSource` — which only issues GETs — cannot consume it. Rather than
 * decode the stream here, this helper returns the raw streaming `Response`; the
 * Planner unit reads `response.body` (a `ReadableStream`) and parses the SSE /
 * JSON-per-event frames itself. Errors before the stream opens still throw
 * {@link ApiError}.
 *
 * (The other feed, `GET /runs/{id}/events`, is intentionally NOT wrapped here —
 * the Run-station unit consumes it with native `EventSource`.)
 */
export async function streamPlanTurn(
  planId: string,
  body: TurnRequest,
  opts?: RequestOptions,
): Promise<Response> {
  const url = buildUrl(`/plans/${enc(planId)}/turns/stream`)
  const response = await fetch(url, {
    method: 'POST',
    headers: { Accept: 'text/event-stream', 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
    signal: opts?.signal,
  })
  if (!response.ok) {
    throw new ApiError(response.status, response.statusText, url, await readBody(response))
  }
  return response
}

/** Absolute (or same-origin) URL of the seam, for callers that build their own
 * requests — notably the Run-station's `EventSource` over `/runs/{id}/events`. */
export function seamUrl(path: string): string {
  return `${BASE_URL}${path}`
}
